spring.application.name=hello-service
server.port=8080
logging.level.com.example=debug

# HTTP client configuration
spring.http.clients.connect-timeout=1s
spring.http.clients.read-timeout=10s
spring.http.serviceclient.user.base-url=http://localhost:8081/
spring.http.serviceclient.greeting.base-url=http://localhost:8082/

# Tracing configuration
spring.task.execution.propagate-context=true
management.observations.annotations.enabled=true

# Application configuration
hello.async=true
hello.open-telemetry-api-usage=false
hello.greeting-client.use-rest-client=true

# For demo only
management.tracing.sampling.probability=1.0
management.otlp.metrics.export.step=1s
# If you want to configure your OTLP urls yourself:
# management.opentelemetry.logging.export.otlp.endpoint=http://your-server-here/v1/logs
# management.opentelemetry.tracing.export.otlp.endpoint=http://your-server-here/v1/traces
# management.otlp.metrics.export.url=http://your-server-here/v1/metrics
