spring.application.name=user-service
server.port=8081
logging.level.com.example=debug

# Tracing configuration
spring.task.execution.propagate-context=true
management.observations.annotations.enabled=true

# For demo only
management.tracing.sampling.probability=1.0
management.otlp.metrics.export.step=10s
