spring.application.name=greeting-service
server.port=8082
logging.level.com.example=debug
spring.task.execution.propagate-context=true
management.observations.annotations.enabled=true
# For demo only
management.tracing.sampling.probability=1.0
management.otlp.metrics.export.step=10s
